# Generated by Django 5.1.1 on 2026-02-08 05:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customuser_daily_report_email_and_more'),
        ('claim', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('model.change', 'Model Change'), ('auth.login', 'Authentication'), ('permission.change', 'Permission Change'), ('system', 'System')], db_index=True, max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('SECURITY', 'Security'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('line_num', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='claim.claim')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('dealership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.dealership')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='claim.journal')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='claim.linetable')),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['dealership', 'occurred_at'], name='audit_event_dealers_0298b1_idx'), models.Index(fields=['claim', 'occurred_at'], name='audit_event_claim_i_4c946f_idx'), models.Index(fields=['line', 'occurred_at'], name='audit_event_line_id_d1e107_idx'), models.Index(fields=['journal', 'occurred_at'], name='audit_event_journal_7e426a_idx'), models.Index(fields=['content_type', 'object_id', 'occurred_at'], name='audit_event_content_86b706_idx'), models.Index(fields=['event_type', 'occurred_at'], name='audit_event_event_t_5473fb_idx'), models.Index(fields=['actor', 'occurred_at'], name='audit_event_actor_i_ba408e_idx')],
            },
        ),
    ]
