# Generated by Django 5.1.1 on 2024-09-16 16:39

import claim.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 50 characters or fewer.', max_length=50, verbose_name='claim type')),
                ('description', models.TextField(help_text='Enter a brief description of the claim type', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Required. Dollar Amount', max_digits=10, null=True)),
                ('parts', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Required. Dollar Amount', max_digits=10, null=True)),
                ('maint', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Required. Dollar Amount', max_digits=10, null=True)),
                ('other', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Required. Dollar Amount', max_digits=10, null=True)),
                ('core', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Required. Dollar Amount', max_digits=10, null=True)),
                ('rental', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Required. Dollar Amount', max_digits=10, null=True)),
                ('sublet', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Required. Dollar Amount', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 50 characters or fewer.', max_length=50, verbose_name='rostatus name')),
                ('description', models.TextField(help_text='Enter a brief description of the status', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 50 characters or fewer', max_length=50, verbose_name='status name')),
                ('description', models.TextField(help_text='Enter a brief description of the status', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_order', models.IntegerField(help_text='Enter Repair Order Number')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('dealership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dealership', verbose_name='dealership name')),
                ('ro_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.rostatus', verbose_name='ro status name')),
                ('claim_tag', models.ManyToManyField(to='claim.tag')),
            ],
        ),
        migrations.CreateModel(
            name='LineTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='line num')),
                ('claim_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Required. Dollar Amount', max_digits=10, null=True, verbose_name='claim total')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('compliant', models.BooleanField(blank=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.claim', verbose_name='claim id')),
                ('claim_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.claimtype', verbose_name='claim type')),
                ('dealership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dealership', verbose_name='dealership name')),
                ('discrepancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.discrepancy')),
                ('service_writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_writer_lines', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_lines', to=settings.AUTH_USER_MODEL)),
                ('claim_status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.status', verbose_name='claim status name')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.claim', verbose_name='claim id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.linetable', verbose_name='line id')),
            ],
            options={
                'ordering': ['created_date', 'line'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.claim', verbose_name='claim id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.linetable', verbose_name='line id')),
            ],
            options={
                'ordering': ['created_date', 'line'],
            },
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='pdf name')),
                ('pdf_file', models.FileField(upload_to=claim.models.user_directory_path)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.claim', verbose_name='claim id')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
