# Generated by Django 5.1.1 on 2024-09-16 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='dealership name')),
                ('address', models.CharField(help_text='Enter an address of the dealership', max_length=30, verbose_name='dealership address')),
                ('main_phone', models.CharField(help_text='Enter an main phone of the dealership', max_length=20, verbose_name='dealership main phone')),
                ('service_phone', models.CharField(help_text='Enter an service phone of the dealership', max_length=20, verbose_name='dealership service phone')),
                ('bac_code', models.CharField(help_text='Enter an bac code of the dealership', max_length=10, verbose_name='dealership bac code')),
                ('labor_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Required. Dollar Amount', max_digits=10, null=True)),
                ('labor_options', models.CharField(help_text='Enter an labor option of the dealership', max_length=30, verbose_name='dealership labor option')),
                ('parts_markup', models.CharField(help_text='Enter an parts markup of the dealership', max_length=30, verbose_name='dealership parts markup')),
                ('ev_restriction', models.CharField(help_text='Enter ev restriction of the dealership', max_length=30, verbose_name='dealership ev restriction')),
                ('md_restriction', models.CharField(help_text='Enter md restriction of the dealership', max_length=30, verbose_name='dealership md restriction')),
                ('wrs_billing_rate', models.CharField(help_text='Enter wrs billing rate of the dealership', max_length=30, verbose_name='dealership wrs billing rate')),
                ('wrs_service_plan', models.CharField(help_text='Enter wrs service plan of the dealership', max_length=100, verbose_name='dealership wrs service plan')),
                ('agreement_date', models.DateField(null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('compliance_enable', models.BooleanField(default=True, help_text='Compliance enable filed')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_users', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
                ('dealership', models.ManyToManyField(blank=True, related_name='users', to='accounts.dealership', verbose_name='dealership')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
