# Generated by Django 5.1.1 on 2025-11-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_report_email',
            field=models.EmailField(blank=True, help_text="Optional override for report delivery email. Defaults to user's primary email.", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receive_daily_report',
            field=models.BooleanField(default=False, help_text='If True, this user will receive the daily report via email.'),
        ),
    ]
