# Generated by Django 5.1.1 on 2024-09-17 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('claim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dummyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='line num')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_order', models.IntegerField(help_text='Enter Repair Order Number')),
                ('created_date', models.DateTimeField()),
                ('dealership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dealership', verbose_name='Dealership name')),
                ('ro_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.rostatus', verbose_name='ro status name')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLineTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='line num')),
                ('claim_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Required. Dollar Amount', max_digits=10, null=True, verbose_name='claim total')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('compliant', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.historicalclaim', verbose_name='claim id')),
                ('claim_status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.status', verbose_name='claim status name')),
                ('claim_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.claimtype', verbose_name='claim type')),
                ('dealership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dealership', verbose_name='dealership name')),
                ('discrepancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.discrepancy')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.historicallinetable', verbose_name='line id')),
            ],
        ),
    ]
