# Generated by Django 5.1.1 on 2026-01-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljournal',
            name='comment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
